### ISSUE TITLE
When calling the image helper multiple times, transformations from previous calls are applied

### ISSUE THREAD

**Issue by erikagiroux** [dakzilla/magento2-intervention-image-helper#1]
When you use the helper more than once on a page, the transformation queue is not cleared between calls.

This happens if you use the helper on the same image or on different images.

It also happens when the calls are made from different template files.

### Steps to reproduce

1. Use the helper on a first image and apply a transformation
```$image = $imageHelper->make('/path/to/image.jpg')->invert()->get();```

2. Use the helper on a second image with different transformations or no transformation at all
```$image2 = $imageHelper->make('/path/to/image2.jpg')->resize(100)->get();```

### Expected behaviour

The first image has inverted colors. The second image is resized to 100px.

### Actual behaviour

The first image has inverted colors. The second image also has inverted colors and is resized to 100px.

**Comment by dakzilla** [comment]
Fixed in 80de3b67d2cf46a265f74a171618dbd139e1391f. Please run `composer update dakzilla/intervention-image-helper` to get the latest version
