### ISSUE TITLE
How to initiate imageHelper from controller or repository class?

### ISSUE THREAD

**Issue by piavgh** [dakzilla/magento2-intervention-image-helper#3]
Hi Simon,

I tried to inject \Dakzilla\Intervention\Helper\Image $imageHelper into a controller but it seems that $imageHelper can not make an image to return an URL.

```
$mediaPath = $this->filesystem->getDirectoryRead(DirectoryList::MEDIA)->getAbsolutePath();
        $imageUrl = $this->imageHelper->make($mediaPath . 'wysiwyg/home/home-main.jpg')
            ->resize(350, null, function ($constraint) {
                $constraint->aspectRatio();
            })
            ->get();
        var_dump($imageUrl); die;
```

This write out NULL.

How can I use this in controller?

Thank you very much

**Comment by dakzilla** [comment]
Hi @piavgh, I will check this out. The helper was made to be used in Magento 2 .phtml Templates on the front-end. I have never tried it out in a controller, but I assume it should still return a valid URL if the source image exists. It may be that the `wysiwyg/home/home-main.jpg` image that I used as a sample in the documentation simply doesn't exist on your Magento 2 installation. Have you [deployed the sample data](http://devdocs.magento.com/guides/v2.1/install-gde/install/sample-data-after-composer.html)?

Again, I will check it out on my side with an updated Magento 2.1.7 and sample data deployed. Thank you

**Comment by dakzilla** [comment]
Hi again @piavgh. I have tested the Helper in a custom controller and it works as expected. Please [see this gist](https://gist.github.com/dakzilla/05d5a03ecaca1aa88b4fc3fd7b4feacd) for the correct usage from a controller. It is the same as using it in a template, except that you need to instanciate the helper yourself. In this example, the image at `pub/media/wysiwyg/home/home-main.jpg` exists on the test Magento 2 environment. The controller in the above Gist returns this URL on my test setup: `http://m2test.local/media/cache/dakzilla_intervention/d41d8cd98f00b204e9800998ecf8427e/home-main.jpg`.

Please review the documentation as I believe it is detailed enough to get started with using this helper. Thank you
